import os
from pathlib import Path
from typing import List, Optional

from onedep_manager.cli.common import Printer
from onedep_manager.config import Config
from onedep_manager.shell.context import ShellContext
from onedep_manager.shell.resolver import EntryPathResolver, UnknownRepositoryError

_SESSION_REPO = "session"

# action name -> repo name, mirroring the cd<suffix>/ls<suffix> bash
# functions from `onedep-manager paths generate-funcs`.
CD_MNEMONICS = {
    "cdt": "tempdep",
    "cdd": "deposit",
    "cdui": "deposit-ui",
    "cda": "archive",
    "cds": _SESSION_REPO,
    "cdup": "upload",
    "cdpkl": "pickles",
}


class NavigationCommands:
    """`cd`-style navigation, mirroring the bash functions generated by
    `onedep-manager paths generate-funcs` -- but changing this shell
    process's own working directory instead of writing a sourceable script.

    Composed into onedep_manager.shell.tui.app.OneDepTuiApp. Requires the
    host object to provide `context`, `resolver`, `config`, and `printer`
    (see the class-level type hints below). Each method takes an
    already-tokenized argument list, matching the `_do_entry`/`_do_scripts`
    convention used elsewhere in the TUI app.
    """

    context: ShellContext
    resolver: EntryPathResolver
    config: Config
    printer: Printer

    def _resolve_repo_path(self, repo: str, identifier: str) -> Path:
        if repo == _SESSION_REPO:
            return Path(self.config.from_site("SITE_WEB_APPS_SESSIONS_PATH")) / identifier
        return self.resolver.resolve(identifier, repo)

    def _cd(self, repo: str, identifier: Optional[str], context_entry: Optional[str] = None) -> None:
        identifier = identifier or self.context.current_entry
        if not identifier:
            self.printer.error(f"Usage: cd {repo} <identifier> (or set one with 'entry')")
            return

        try:
            path = self._resolve_repo_path(repo, identifier)
        except UnknownRepositoryError as exc:
            self.printer.error(str(exc))
            return
        except Exception as exc:
            self.printer.error(f"cd {repo}: {exc}")
            return

        if not path.is_dir():
            self.printer.error(f"cd {repo}: directory not found: {path}")
            return

        os.chdir(path)
        self.context.set_entry(context_entry if context_entry is not None else identifier)

    def do_cd(self, args: List[str]) -> None:
        """Cd into a repository path for an entry: `cd <repo> [identifier]`
        Uses the current entry (see `entry`) if identifier is omitted."""
        if not args or len(args) > 2:
            known = ", ".join(sorted(set(self.resolver.known_repos) | {_SESSION_REPO}))
            self.printer.error(f"Usage: cd <repo> [identifier]\nValid repos: {known}")
            return
        repo, identifier = args[0], (args[1] if len(args) == 2 else None)
        self._cd(repo, identifier)

    def do_cd_mnemonic(self, action: str, args: List[str]) -> None:
        """Cd into the repository for `action`'s mnemonic (see CD_MNEMONICS):
        `cdd [identifier]` (uses the current entry if identifier is omitted)."""
        if len(args) > 1:
            self.printer.error(f"Usage: {action} [identifier]")
            return
        self._cd(CD_MNEMONICS[action], args[0] if args else None)

    def do_cdwfi(self, args: List[str]) -> None:
        """Cd into a workflow instance directory: `cdwfi <wfinst_id>` (uses
        the current entry) or `cdwfi <entry_id> <wfinst_id>`."""
        if len(args) == 1:
            entry_id, wfinst_id = self.context.current_entry, args[0]
        elif len(args) == 2:
            entry_id, wfinst_id = args
        else:
            self.printer.error("Usage: cdwfi [entry_id] <wfinst_id>")
            return

        if not entry_id:
            self.printer.error("Usage: cdwfi [entry_id] <wfinst_id> (or set one with 'entry')")
            return

        self._cd("wfinst", f"{entry_id}:{wfinst_id}", context_entry=entry_id)
