import os
import shlex
from pathlib import Path
from typing import Optional

from onedep_manager.cli.common import Printer
from onedep_manager.config import Config
from onedep_manager.shell.context import ShellContext
from onedep_manager.shell.resolver import EntryPathResolver, UnknownRepositoryError

_SESSION_REPO = "session"

# suffix -> repo name, mirroring the cd<suffix>/ls<suffix> bash functions
# from `onedep-manager paths generate-funcs`.
_MNEMONICS = {
    "t": "tempdep",
    "d": "deposit",
    "ui": "deposit-ui",
    "a": "archive",
    "s": _SESSION_REPO,
    "up": "upload",
    "pkl": "pickles",
}


class NavigationCommands:
    """`cd`-style navigation, mirroring the bash functions generated by
    `onedep-manager paths generate-funcs` -- but changing this shell
    process's own working directory instead of writing a sourceable script.

    Composed into onedep_manager.shell.app.OneDepShell. Requires the host
    object to provide `context`, `resolver`, `config`, `printer`, `do_files`,
    and `_update_prompt` (see the class-level type hints below).
    """

    context: ShellContext
    resolver: EntryPathResolver
    config: Config
    printer: Printer

    def _resolve_repo_path(self, repo: str, identifier: str) -> Path:
        if repo == _SESSION_REPO:
            return Path(self.config.from_site("SITE_WEB_APPS_SESSIONS_PATH")) / identifier
        return self.resolver.resolve(identifier, repo)

    def _cd(self, repo: str, identifier: Optional[str], context_entry: Optional[str] = None) -> None:
        identifier = identifier or self.context.current_entry
        if not identifier:
            self.printer.error(f"Usage: cd {repo} <identifier> (or set one with 'entry')")
            return

        try:
            path = self._resolve_repo_path(repo, identifier)
        except UnknownRepositoryError as exc:
            self.printer.error(str(exc))
            return
        except Exception as exc:
            self.printer.error(f"cd {repo}: {exc}")
            return

        if not path.is_dir():
            self.printer.error(f"cd {repo}: directory not found: {path}")
            return

        os.chdir(path)
        self.context.set_entry(context_entry if context_entry is not None else identifier)
        self._update_prompt()

    def do_cd(self, arg) -> None:
        """Cd into a repository path for an entry: `cd <repo> [identifier]`
        Uses the current entry (see `entry`) if identifier is omitted."""
        args = shlex.split(str(arg))
        if not args or len(args) > 2:
            known = ", ".join(sorted(set(self.resolver.known_repos) | {_SESSION_REPO}))
            self.printer.error(f"Usage: cd <repo> [identifier]\nValid repos: {known}")
            return
        repo, identifier = args[0], (args[1] if len(args) == 2 else None)
        self._cd(repo, identifier)

    def complete_cd(self, text, line, begidx, endidx):
        repos = sorted(set(self.resolver.known_repos) | {_SESSION_REPO})
        return [r for r in repos if r.startswith(text)]

    def do_cdwfi(self, arg) -> None:
        """Cd into a workflow instance directory: `cdwfi <wfinst_id>` (uses
        the current entry) or `cdwfi <entry_id> <wfinst_id>`."""
        args = shlex.split(str(arg))
        if len(args) == 1:
            entry_id, wfinst_id = self.context.current_entry, args[0]
        elif len(args) == 2:
            entry_id, wfinst_id = args
        else:
            self.printer.error("Usage: cdwfi [entry_id] <wfinst_id>")
            return

        if not entry_id:
            self.printer.error("Usage: cdwfi [entry_id] <wfinst_id> (or set one with 'entry')")
            return

        self._cd("wfinst", f"{entry_id}:{wfinst_id}", context_entry=entry_id)

    def do_ls(self, arg) -> None:
        """Alias for `files list [args...]`."""
        self.do_files(f"list {arg}")

    def do_ff(self, arg) -> None:
        """Alias for `files find [args...]`."""
        self.do_files(f"find {arg}")


def _make_mnemonic(suffix: str, repo: str):
    def handler(self, arg) -> None:
        args = shlex.split(str(arg))
        if len(args) > 1:
            self.printer.error(f"Usage: cd{suffix} [identifier]")
            return
        self._cd(repo, args[0] if args else None)

    handler.__doc__ = f"Cd into the '{repo}' path for an entry: `cd{suffix} [identifier]` (uses the current entry if omitted)."
    handler.__name__ = f"do_cd{suffix}"
    return handler


for _suffix, _repo in _MNEMONICS.items():
    setattr(NavigationCommands, f"do_cd{_suffix}", _make_mnemonic(_suffix, _repo))

del _suffix, _repo
