import os
import click
from rich.console import Console
from pathlib import Path

from onedep_manager.cli.common import ConsolePrinter
from onedep_manager.config import Config
from onedep_manager.packages import get_package

from wwpdb.io.locator.PathInfo import PathInfo
from wwpdb.io.locator.ChemRefPathInfo import ChemRefPathInfo


@click.group(name="paths", help="Get common OneDep paths")
def paths_group():
    """`paths` command group"""


@paths_group.command(name="get", help="Get the current paths")
@click.argument("type_")
@click.argument("identifier")
@click.option("-i", "--site", "site", help="wwPDB site ID (e.g. WWPDB_DEPLOY_TEST_RU). Defaults to the current site.")
def get(type_, identifier, site):
    """`get` command handler
    If no error happens, this must return the path only.
    """
    c = Console()
    printer = ConsolePrinter(console=c)
    config = Config()
    pathinfo = PathInfo()
    ccdpathinfo = ChemRefPathInfo()

    if type_ not in ('tempdep', 'deposit', 'archive', 'upload', 'pickles', 'wfinst', 'session', 'ccid', 'package', 'wfxml', 'tool'):
        printer.error(f"Invalid path type: {type_}\nValid types are: tempdep, deposit, archive, upload, wfinst, session, ccid, package, wfxml, tool")
        return

    if type_ == 'tempdep':
        print(pathinfo.getTempDepPath(dataSetId=identifier))
    elif type_ == 'deposit':
        print(pathinfo.getDepositPath(dataSetId=identifier))
    elif type_ == 'archive':
        print(pathinfo.getArchivePath(dataSetId=identifier))
    elif type_ == 'upload':
        deposit_path = config.from_site("SITE_ARCHIVE_STORAGE_PATH")
        print(os.path.join(deposit_path, "deposit", "temp_files", "deposition_uploads", identifier))
    elif type_ == 'pickles':
        deposit_path = config.from_site("SITE_ARCHIVE_STORAGE_PATH")
        print(os.path.join(deposit_path, "deposit", "temp_files", "deposition-v-200", identifier))
    elif type_ == 'wfinst':
        dep_id = identifier.split(":")[0]
        wf_instance = identifier.split(":")[1]
        print(pathinfo.getInstancePath(dataSetId=dep_id, wfInstanceId=wf_instance))
    elif type_ == 'session':
        print(os.path.join(config.from_site("SITE_WEB_APPS_SESSIONS_PATH"), identifier))
    elif type_ == 'ccid':
        print(ccdpathinfo.getFilePath(idCode=identifier))
    elif type_ == 'package':
        print(get_package(identifier).path)
    elif type_ == 'wfxml':
        print(os.path.join(config.from_site("SITE_WF_XML_PATH"), f"{identifier}.xml"))
    elif type_ == 'tool':
        print("Not implemented yet")


@paths_group.command(name="generate-funcs", help="Generate .onedep_funcs bash file with environment variables and helper functions")
def generate_funcs():
    """`generate-funcs` command handler
    Creates a .onedep_funcs file in the home directory with export statements
    and helper functions for cd and ls operations.
    """
    c = Console()
    printer = ConsolePrinter(console=c)
    config = Config()
    mock_dep_id = "D_000000"
    pi = PathInfo()

    # Define path mappings: (type, variable_suffix, function_suffix, base_path_getter)
    # Regular paths that get cd/ls functions
    regular_path_mappings = [
        ('tempdep', 'TEMPDEP', 't', lambda: pi.getTempDepPath(dataSetId=mock_dep_id).rsplit('/', 1)[0]),
        ('deposit', 'DEPOSIT', 'd', lambda: pi.getDepositPath(dataSetId=mock_dep_id).rsplit('/', 1)[0]),
        ('deposit', 'DEPOSIT_UI', 'ui', lambda: pi.getDepositUIPath(dataSetId=mock_dep_id).rsplit('/', 1)[0]),
        ('archive', 'ARCHIVE', 'a', lambda: pi.getArchivePath(dataSetId=mock_dep_id).rsplit('/', 1)[0]),
        ('session', 'SESSION', 's', lambda: config.from_site("SITE_WEB_APPS_SESSIONS_PATH")),
        ('upload', 'UPLOAD', 'up', lambda: pi.getDirPath(dataSetId=mock_dep_id, fileSource='uploads').rsplit('/', 1)[0]),
        ('pickles', 'PICKLES', 'pkl', lambda: pi.getDirPath(dataSetId=mock_dep_id, fileSource='pickles').rsplit('/', 1)[0]),
        ('wfinst', 'WFINST', 'wfi', lambda: pi.getInstancePath(dataSetId=mock_dep_id, wfInstanceId='W_001').rsplit('/', 3)[0]),
    ]

    # Special paths that get vi functions or custom handling
    special_path_mappings = [
        ('ccid', 'CCID', 'ccid', lambda: ChemRefPathInfo().getFilePath(idCode='ABC').rsplit('/', 3)[0]),
        ('wfxml', 'WFXML', 'wfx', lambda: config.from_site("SITE_WF_XML_PATH")),
    ]

    all_path_mappings = regular_path_mappings + special_path_mappings

    # Generate the bash file content
    lines = [
        "#!/bin/bash",
        "# OneDep Manager Path Functions",
        "# This file is auto-generated by 'onedep paths generate-funcs'",
        "# Source this file in your .bashrc or .bash_profile:",
        "#   source ~/.onedep_funcs",
        "",
    ]

    # Add export statements
    for type_name, var_suffix, func_suffix, path_getter in all_path_mappings:
        try:
            base_path = path_getter()
            lines.append(f"export ODM_{var_suffix}=\"{base_path}\"")
        except Exception as e:
            printer.error(f"Failed to get path for {type_name}: {e}")
            continue

    lines.append("")

    # Add cd functions for regular paths
    for type_name, var_suffix, func_suffix, _ in regular_path_mappings:
        lines.extend([
            f"function cd{func_suffix}() {{",
            f"    local path=\"$ODM_{var_suffix}/$1\"",
            f"    if [ ! -d \"$path\" ]; then",
            f"        echo \"Error: directory not found: $path\"",
            f"        return 1",
            f"    fi",
            f"    cd \"$path\" || return 1",
            f"}}",
            "",
        ])

    # Add ls functions for regular paths
    for type_name, var_suffix, func_suffix, _ in regular_path_mappings:
        lines.extend([
            f"function ls{func_suffix}() {{",
            f"    local path=\"$ODM_{var_suffix}/$1\"",
            f"    if [ ! -d \"$path\" ]; then",
            f"        echo \"Error: directory not found: $path\"",
            f"        return 1",
            f"    fi",
            f"    ls -lah \"$path\"",
            f"}}",
            "",
        ])

    # viwfi: takes two parameters (dep_id and wfinst_id)
    lines.extend([
        "function cdwfi() {",
        "    local dep_id=\"$1\"",
        "    local wfinst_id=\"$2\"",
        "    local path=\"$ODM_WFINST/$dep_id/$wfinst_id\"",
        "    if [ ! -d \"$path\" ]; then",
        "        echo \"Error: directory not found: $path\"",
        "        return 1",
        "    fi",
        "    # Open the directory in vi (will show file browser or fail gracefully)",
        "    cd \"$path\" || return 1",
        "}",
        "",
        "function lswfi() {",
        "    local dep_id=\"$1\"",
        "    local wfinst_id=\"$2\"",
        "    local path=\"$ODM_WFINST/$dep_id/$wfinst_id\"",
        "    if [ ! -d \"$path\" ]; then",
        "        echo \"Error: directory not found: $path\"",
        "        return 1",
        "    fi",
        "    # Open the directory in vi (will show file browser or fail gracefully)",
        "    ls -lah \"$path\"",
        "}",
        "",
    ])

    # Add special vi functions
    # viccid: path structure is <base>/<id_initial>/<full_id>
    lines.extend([
        "function viccid() {",
        "    if [ -z \"$1\" ]; then",
        "        echo \"Error: ccid identifier required\"",
        "        return 1",
        "    fi",
        "    local id=\"$1\"",
        "    local id_initial=\"${id:0:1}\"",
        "    local path=\"$ODM_CCID/$id_initial/$id\"",
        "    if [ ! -f \"$path\" ]; then",
        "        echo \"Error: file not found: $path\"",
        "        return 1",
        "    fi",
        "    vi \"$path\"",
        "}",
        "",
    ])

    # viwfx: opens wfxml file
    lines.extend([
        "function viwfx() {",
        "    if [ -z \"$1\" ]; then",
        "        echo \"Error: workflow identifier required\"",
        "        return 1",
        "    fi",
        "    local path=\"$ODM_WFXML/$1.xml\"",
        "    if [ ! -f \"$path\" ]; then",
        "        echo \"Error: file not found: $path\"",
        "        return 1",
        "    fi",
        "    vi \"$path\"",
        "}",
        "",
    ])

    # Write to file
    output_file = Path.home() / ".onedep_funcs"
    try:
        with open(output_file, 'w') as f:
            f.write('\n'.join(lines))
        os.chmod(output_file, 0o755)
        printer.info(f"Successfully created {output_file}")
        printer.info("To use these functions, add this to your .bashrc or .bash_profile:")
        printer.info(f"  source {output_file}")
    except Exception as e:
        printer.error(f"Failed to write {output_file}: {e}")
